// <auto-generated />
using System;
using AnnotationStore.Annotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnnotationStore.Migrations
{
    [DbContext(typeof(AnnotationDbContext))]
    [Migration("20260911235928_AddRegionOfInterest")]
    partial class AddRegionOfInterest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnnotationStore.Annotations.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LineStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineThickness")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlideId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlideId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("AnnotationStore.CellCounts.CellCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DotSize")
                        .HasColumnType("integer");

                    b.Property<string>("Dots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("LocationX")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationY")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlideId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WithAnnotation")
                        .HasColumnType("boolean");

                    b.Property<bool>("WithRoi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SlideId");

                    b.ToTable("CellCounts");
                });

            modelBuilder.Entity("AnnotationStore.CellCounts.RegionOfInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellCountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CellCountId")
                        .IsUnique();

                    b.ToTable("RegionsOfInterest");
                });

            modelBuilder.Entity("AnnotationStore.CellCounts.RegionOfInterest", b =>
                {
                    b.HasOne("AnnotationStore.CellCounts.CellCount", null)
                        .WithOne("RegionOfInterest")
                        .HasForeignKey("AnnotationStore.CellCounts.RegionOfInterest", "CellCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnnotationStore.CellCounts.CellCount", b =>
                {
                    b.Navigation("RegionOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
